// micro-C example 7 -- an infinite loop

void main() {
    int i;
    i = 0;
    for (i = 0; i < 10; i++) {
        print i;
    }
    print 'N';
}

/* Code generated by the new continuation-based compiler:

      LDARGS; CALL (0,L1); STOP; 
  L1: CSTI 0; GETBP; CSTI 0; STI; INCSP -1; 
  L2: GETBP; GETBP; LDI; CSTI 1; ADD; STI; INCSP -1; GOTO L2
*/

